import type { Metadata } from "next";
import {  Geist_Mono,Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${geistMono.variable} antialiased  !bg-stone-100 h-full pt30`}
      >
        <Header /> {/* Site header/nav */}
        <main className="max-w-7xl mx-auto py-10 mt-5">{children}</main>
      </body>
    </html>
  );
}
